---
title: "Modein Conmebol"
author: "Luis Noguera"
date: "5/31/2020"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
library(tidyverse)
library(plotly)
library(tidymodels)
library(doParallel)

conmebol_raw <- read_csv("conmebol.csv") %>%
  select(-X1, -rating) 

conmebol_raw %>%
  mutate(value = parse_number(value)) %>% View()
```


# Data Cleaning

```{r}

# Cleaning the value column deleting text and getting the right value of the player.
conmebol <- conmebol_raw %>%
  mutate(value = parse_number(value), 
         value = case_when(value < 99 ~ value * 1000000, 
                           TRUE ~ value * 1000)) %>%
  na_if(., 0) %>%
  select(-height, -name)
  

# Quick view and summary of the data at hand.
skimr::skim(conmebol)

```

# Recipes and Rsample Package

## Data Split

```{r}

set.seed(415)

# Split data into training and testing data sets. 
conmebol_split <- initial_split(conmebol, prop = .8, strata = foot)
conmebol_train <- training(conmebol_split) 
conmebol_test <- testing(conmebol_split)

# Creates ten folds of the training data set.
tidy_kfolds <- vfold_cv(conmebol_train)

```

## Preprocessing, feature engineering and eliminiation


```{r}

conmebol_rec <- recipe(value ~ ., data = conmebol_train) %>%
  update_role(id, new_role = "id") %>%  # Updating id roles variable
  step_dummy(all_nominal(), -all_outcomes()) %>%
  step_knnimpute(value, neighbors = 5) %>%
  step_corr(all_predictors(), -all_outcomes()) %>%
  step_normalize(all_predictors(), -all_outcomes()) 
  
conmebol_prep <- conmebol_rec %>% prep()

bake(conmebol_prep, conmebol_train)

workflow <- workflow() %>%
  add_recipe(conmebol_rec)

```

# Parsnip Package

## Fitting Statistical Models - 

- Regularization Model - Lasso Regression
- Random Forest Model - XGBoost



# Lasso Regression


```{r}

lasso_spec <- linear_reg(penalty = 0.1, mixture = 1) %>%
  set_engine('glmnet')

lasso_fit <- workflow %>%
  add_model(lasso_spec) %>%
  fit(data = conmebol_train)

lasso_fit %>% 
  pull_workflow_fit()

```


# Tuning Lasso

```{r}
set.seed(415)
doParallel::registerDoParallel()

lasso_tune <- linear_reg(
  mode = 'regression',
  penalty = tune(),
  mixture = 1
) %>%
  set_engine('glmnet')

lambda_grid <- grid_regular(penalty(), levels = 50)

lasso_grid <- tune_grid(
  workflow %>%
    add_model(lasso_tune),
  resamples = bootstrap_conmebol,
  grid = lambda_grid
)



```


```{r}


rf_spec <- rand_forest(
  min_n = tune(),
  
)




```

