---
title: "Data Preprocessing Exploration"
author: "Nicolas Kaswalder"
date: "8/12/2020"
output: html_document
---

```{r}

#Look for missing data
plot_missing <- aggr(Conmebol, col = c('navyblue', 'red'), numbers = T, sortVars = T)

# imputation using the mice package - mean imputation
mean_impute <- mice(Conmebol, m = 5, meth = 'mean' )
# look at the values
mean_impute$imp

# imputation using the mice package - regression ignoring model error
regression_impute <- mice(Conmebol, m = 5, meth = 'norm.predict')
# look at the values
regression_impute$imp

# imputation using the mice package - perturbation impute
pert_impute <- mice(Conmebol, m = 5, meth = 'norm.nob')
# look at the values
pert_impute$imp


# Conmebol with mean impute
Mean_Conmebol<- complete(mean_impute)
# Conmebol with regression prediction impute
Regression_Conmebol <- complete(regression_impute)
# Conmebol with pertubation impute
Perturbation_Conmebol <- complete(pert_impute)

```


## User Defined Functions Examples


```{r}

# Value by Best Position
Conmebol %>% 
    drop_na() %>% 
  filter(nationality == nationality) %>% 
  mutate(best_position = fct_reorder(best_position, value)) %>% 
  ggplot(aes(best_position, value, fill = position)) +
     ggtitle("Value by Best Position") +
  geom_boxplot() +
  scale_y_continuous(labels = scales::dollar) +
  theme_minimal()+
    theme(legend.background = element_rect(fill="gray90", size=.5, linetype="dotted",))+
     theme(legend.justification=c(0,0.5))+
  theme(
    plot.title = element_text(color="black", size=14, face="bold"),
    axis.title.x = element_text(color="dark red", size=12, face="bold"),
    axis.title.y = element_text(color="dark red", size=12, face="bold"))+
  labs(x = 'Best Position', y = 'Value') +
  coord_flip()+
    scale_fill_discrete(name="Best Position")
  
```

```{r}

# Value per Position & Nationality
Conmebol %>% 
    drop_na() %>% 
  filter(nationality == nationality) %>% 
  mutate(nationality = fct_reorder(nationality, -value)) %>% 
  ggplot(aes(nationality, value, fill = position)) +
      ggtitle("Value per Position & Nationality") +
  geom_boxplot() +
  scale_y_continuous(labels = scales::dollar) +
    theme_minimal()+
    theme(legend.background = element_rect(fill="gray90", size=.5, linetype="dotted"))+
    theme(legend.justification=c(1,0), legend.position=c(1,0.6))+
  theme(
    plot.title = element_text(color="black", size=14, face="bold"),
    axis.title.x = element_text(color="dark red", size=12, face="bold"),
    axis.title.y = element_text(color="dark red", size=12, face="bold"))+
  labs(x = 'Nationality', y = 'Value') +
    scale_fill_discrete(name="Position")

```

```{r}

#Average value per Position
Conmebol %>% 
  drop_na() %>% 
  filter(nationality == nationality) %>%
    group_by(best_position) %>% 
    summarise(value=mean(value)) %>% 
    drop_na() %>% 
    mutate(best_position = fct_reorder(best_position, -value)) %>% 
    ggplot(aes(x= best_position, y = value, color = best_position))+
    geom_point(size = 5)+
    geom_segment(aes(x=best_position, xend = best_position, y = value, yend = 0))+
    theme_minimal()+
     ggtitle("Average Value Per Position") +
     theme(legend.position = "none")+
  theme(
    plot.title = element_text(color="black", size=14, face="bold"),
    axis.title.x = element_text(color="dark blue", size=12, face="bold"),
    axis.title.y = element_text(color="dark blue", size=12, face="bold"))+
  labs(x = 'Best Position', y = 'Value') +
  scale_y_continuous(n.breaks = 10,labels = scales::dollar)+
    scale_fill_discrete(name="Best Position")

#Max Value per Position
Conmebol %>% 
  drop_na() %>% 
  filter(nationality == nationality, position == position) %>%
    group_by(best_position) %>% 
    summarise(value=max(value)) %>% 
    drop_na() %>% 
    mutate(best_position = fct_reorder(best_position, -value)) %>% 
    ggplot(aes(x= best_position, y = value, color = best_position))+
    geom_point(size = 5)+
    geom_segment(aes(x=best_position, xend = best_position, y = value, yend = 0))+
    theme_minimal()+
     ggtitle("Max Value Per Position") +
    theme(legend.position = "none")+
  theme(
    plot.title = element_text(color="black", size=14, face="bold"),
    axis.title.x = element_text(color="dark blue", size=12, face="bold"),
    axis.title.y = element_text(color="dark blue", size=12, face="bold"))+
  labs(x = 'Best Position', y = 'Value') +
  scale_y_continuous(labels = scales::dollar)+
    scale_fill_discrete(name="Best Position")



  
```
)

